docking_score_regression_model:
  num_transformer_blocks: 3
  embed_dim: 384
  num_heads: 6
  ffn_hidden_dim: 1024
  dropout: 0.1
  max_smiles_tokens: 100
  max_protein_tokens: 1390
moses_vae_model:
  embed_dim: 384
  max_smiles_tokens: 100
  max_protein_tokens: 1390
decoder_only_model:
  embed_dim: 384
  max_smiles_tokens: 100
  max_protein_tokens: 1390
  transformer_layer_used: 0
  moses_vae_file: "ds_2024-12-23_22-52-47/smiles_vae_chembl_35_000.pt"
  docking_score_regression_file: "2024-12-23_22-52-47/model_epoch_6.pth"
