docking_score_regression_model:
  num_transformer_layers: 3
  embed_dim: 384
  num_heads: 6
  ffn_hidden_dim: 1024
  dropout: 0.1
  max_smiles_tokens: 100
  max_protein_tokens: 1390
generation_model:
  embed_dim: 384
  max_smiles_tokens: 100
  max_protein_tokens: 1390